/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NonAutoriseRouteImport } from './routes/non-autorise'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangerMotDePasseRouteImport } from './routes/changer-mot-de-passe'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTechRouteImport } from './routes/_authed.tech'
import { Route as AuthedProfilRouteImport } from './routes/_authed.profil'
import { Route as AuthedChefRouteImport } from './routes/_authed.chef'
import { Route as AuthedTechMissionsRouteImport } from './routes/_authed.tech.missions'
import { Route as AuthedChefTechsRouteImport } from './routes/_authed.chef.techs'
import { Route as AuthedChefInterventionsRouteImport } from './routes/_authed.chef.interventions'
import { Route as AuthedChefDashboardRouteImport } from './routes/_authed.chef.dashboard'
import { Route as AuthedChefClientsRouteImport } from './routes/_authed.chef.clients'
import { Route as AuthedTechMissionDetailIdRouteImport } from './routes/_authed.tech.mission-detail.$id'
import { Route as AuthedChefInterventionDetailIdRouteImport } from './routes/_authed.chef.intervention-detail.$id'
import { Route as AuthedChefClientDetailIdRouteImport } from './routes/_authed.chef.client-detail.$id'

const NonAutoriseRoute = NonAutoriseRouteImport.update({
  id: '/non-autorise',
  path: '/non-autorise',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangerMotDePasseRoute = ChangerMotDePasseRouteImport.update({
  id: '/changer-mot-de-passe',
  path: '/changer-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTechRoute = AuthedTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilRoute = AuthedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChefRoute = AuthedChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTechMissionsRoute = AuthedTechMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthedTechRoute,
} as any)
const AuthedChefTechsRoute = AuthedChefTechsRouteImport.update({
  id: '/techs',
  path: '/techs',
  getParentRoute: () => AuthedChefRoute,
} as any)
const AuthedChefInterventionsRoute = AuthedChefInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AuthedChefRoute,
} as any)
const AuthedChefDashboardRoute = AuthedChefDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedChefRoute,
} as any)
const AuthedChefClientsRoute = AuthedChefClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedChefRoute,
} as any)
const AuthedTechMissionDetailIdRoute =
  AuthedTechMissionDetailIdRouteImport.update({
    id: '/mission-detail/$id',
    path: '/mission-detail/$id',
    getParentRoute: () => AuthedTechRoute,
  } as any)
const AuthedChefInterventionDetailIdRoute =
  AuthedChefInterventionDetailIdRouteImport.update({
    id: '/intervention-detail/$id',
    path: '/intervention-detail/$id',
    getParentRoute: () => AuthedChefRoute,
  } as any)
const AuthedChefClientDetailIdRoute =
  AuthedChefClientDetailIdRouteImport.update({
    id: '/client-detail/$id',
    path: '/client-detail/$id',
    getParentRoute: () => AuthedChefRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/login': typeof LoginRoute
  '/non-autorise': typeof NonAutoriseRoute
  '/chef': typeof AuthedChefRouteWithChildren
  '/profil': typeof AuthedProfilRoute
  '/tech': typeof AuthedTechRouteWithChildren
  '/chef/clients': typeof AuthedChefClientsRoute
  '/chef/dashboard': typeof AuthedChefDashboardRoute
  '/chef/interventions': typeof AuthedChefInterventionsRoute
  '/chef/techs': typeof AuthedChefTechsRoute
  '/tech/missions': typeof AuthedTechMissionsRoute
  '/chef/client-detail/$id': typeof AuthedChefClientDetailIdRoute
  '/chef/intervention-detail/$id': typeof AuthedChefInterventionDetailIdRoute
  '/tech/mission-detail/$id': typeof AuthedTechMissionDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/login': typeof LoginRoute
  '/non-autorise': typeof NonAutoriseRoute
  '/chef': typeof AuthedChefRouteWithChildren
  '/profil': typeof AuthedProfilRoute
  '/tech': typeof AuthedTechRouteWithChildren
  '/chef/clients': typeof AuthedChefClientsRoute
  '/chef/dashboard': typeof AuthedChefDashboardRoute
  '/chef/interventions': typeof AuthedChefInterventionsRoute
  '/chef/techs': typeof AuthedChefTechsRoute
  '/tech/missions': typeof AuthedTechMissionsRoute
  '/chef/client-detail/$id': typeof AuthedChefClientDetailIdRoute
  '/chef/intervention-detail/$id': typeof AuthedChefInterventionDetailIdRoute
  '/tech/mission-detail/$id': typeof AuthedTechMissionDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/login': typeof LoginRoute
  '/non-autorise': typeof NonAutoriseRoute
  '/_authed/chef': typeof AuthedChefRouteWithChildren
  '/_authed/profil': typeof AuthedProfilRoute
  '/_authed/tech': typeof AuthedTechRouteWithChildren
  '/_authed/chef/clients': typeof AuthedChefClientsRoute
  '/_authed/chef/dashboard': typeof AuthedChefDashboardRoute
  '/_authed/chef/interventions': typeof AuthedChefInterventionsRoute
  '/_authed/chef/techs': typeof AuthedChefTechsRoute
  '/_authed/tech/missions': typeof AuthedTechMissionsRoute
  '/_authed/chef/client-detail/$id': typeof AuthedChefClientDetailIdRoute
  '/_authed/chef/intervention-detail/$id': typeof AuthedChefInterventionDetailIdRoute
  '/_authed/tech/mission-detail/$id': typeof AuthedTechMissionDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changer-mot-de-passe'
    | '/login'
    | '/non-autorise'
    | '/chef'
    | '/profil'
    | '/tech'
    | '/chef/clients'
    | '/chef/dashboard'
    | '/chef/interventions'
    | '/chef/techs'
    | '/tech/missions'
    | '/chef/client-detail/$id'
    | '/chef/intervention-detail/$id'
    | '/tech/mission-detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changer-mot-de-passe'
    | '/login'
    | '/non-autorise'
    | '/chef'
    | '/profil'
    | '/tech'
    | '/chef/clients'
    | '/chef/dashboard'
    | '/chef/interventions'
    | '/chef/techs'
    | '/tech/missions'
    | '/chef/client-detail/$id'
    | '/chef/intervention-detail/$id'
    | '/tech/mission-detail/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/changer-mot-de-passe'
    | '/login'
    | '/non-autorise'
    | '/_authed/chef'
    | '/_authed/profil'
    | '/_authed/tech'
    | '/_authed/chef/clients'
    | '/_authed/chef/dashboard'
    | '/_authed/chef/interventions'
    | '/_authed/chef/techs'
    | '/_authed/tech/missions'
    | '/_authed/chef/client-detail/$id'
    | '/_authed/chef/intervention-detail/$id'
    | '/_authed/tech/mission-detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ChangerMotDePasseRoute: typeof ChangerMotDePasseRoute
  LoginRoute: typeof LoginRoute
  NonAutoriseRoute: typeof NonAutoriseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/non-autorise': {
      id: '/non-autorise'
      path: '/non-autorise'
      fullPath: '/non-autorise'
      preLoaderRoute: typeof NonAutoriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changer-mot-de-passe': {
      id: '/changer-mot-de-passe'
      path: '/changer-mot-de-passe'
      fullPath: '/changer-mot-de-passe'
      preLoaderRoute: typeof ChangerMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tech': {
      id: '/_authed/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof AuthedTechRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profil': {
      id: '/_authed/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthedProfilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chef': {
      id: '/_authed/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof AuthedChefRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tech/missions': {
      id: '/_authed/tech/missions'
      path: '/missions'
      fullPath: '/tech/missions'
      preLoaderRoute: typeof AuthedTechMissionsRouteImport
      parentRoute: typeof AuthedTechRoute
    }
    '/_authed/chef/techs': {
      id: '/_authed/chef/techs'
      path: '/techs'
      fullPath: '/chef/techs'
      preLoaderRoute: typeof AuthedChefTechsRouteImport
      parentRoute: typeof AuthedChefRoute
    }
    '/_authed/chef/interventions': {
      id: '/_authed/chef/interventions'
      path: '/interventions'
      fullPath: '/chef/interventions'
      preLoaderRoute: typeof AuthedChefInterventionsRouteImport
      parentRoute: typeof AuthedChefRoute
    }
    '/_authed/chef/dashboard': {
      id: '/_authed/chef/dashboard'
      path: '/dashboard'
      fullPath: '/chef/dashboard'
      preLoaderRoute: typeof AuthedChefDashboardRouteImport
      parentRoute: typeof AuthedChefRoute
    }
    '/_authed/chef/clients': {
      id: '/_authed/chef/clients'
      path: '/clients'
      fullPath: '/chef/clients'
      preLoaderRoute: typeof AuthedChefClientsRouteImport
      parentRoute: typeof AuthedChefRoute
    }
    '/_authed/tech/mission-detail/$id': {
      id: '/_authed/tech/mission-detail/$id'
      path: '/mission-detail/$id'
      fullPath: '/tech/mission-detail/$id'
      preLoaderRoute: typeof AuthedTechMissionDetailIdRouteImport
      parentRoute: typeof AuthedTechRoute
    }
    '/_authed/chef/intervention-detail/$id': {
      id: '/_authed/chef/intervention-detail/$id'
      path: '/intervention-detail/$id'
      fullPath: '/chef/intervention-detail/$id'
      preLoaderRoute: typeof AuthedChefInterventionDetailIdRouteImport
      parentRoute: typeof AuthedChefRoute
    }
    '/_authed/chef/client-detail/$id': {
      id: '/_authed/chef/client-detail/$id'
      path: '/client-detail/$id'
      fullPath: '/chef/client-detail/$id'
      preLoaderRoute: typeof AuthedChefClientDetailIdRouteImport
      parentRoute: typeof AuthedChefRoute
    }
  }
}

interface AuthedChefRouteChildren {
  AuthedChefClientsRoute: typeof AuthedChefClientsRoute
  AuthedChefDashboardRoute: typeof AuthedChefDashboardRoute
  AuthedChefInterventionsRoute: typeof AuthedChefInterventionsRoute
  AuthedChefTechsRoute: typeof AuthedChefTechsRoute
  AuthedChefClientDetailIdRoute: typeof AuthedChefClientDetailIdRoute
  AuthedChefInterventionDetailIdRoute: typeof AuthedChefInterventionDetailIdRoute
}

const AuthedChefRouteChildren: AuthedChefRouteChildren = {
  AuthedChefClientsRoute: AuthedChefClientsRoute,
  AuthedChefDashboardRoute: AuthedChefDashboardRoute,
  AuthedChefInterventionsRoute: AuthedChefInterventionsRoute,
  AuthedChefTechsRoute: AuthedChefTechsRoute,
  AuthedChefClientDetailIdRoute: AuthedChefClientDetailIdRoute,
  AuthedChefInterventionDetailIdRoute: AuthedChefInterventionDetailIdRoute,
}

const AuthedChefRouteWithChildren = AuthedChefRoute._addFileChildren(
  AuthedChefRouteChildren,
)

interface AuthedTechRouteChildren {
  AuthedTechMissionsRoute: typeof AuthedTechMissionsRoute
  AuthedTechMissionDetailIdRoute: typeof AuthedTechMissionDetailIdRoute
}

const AuthedTechRouteChildren: AuthedTechRouteChildren = {
  AuthedTechMissionsRoute: AuthedTechMissionsRoute,
  AuthedTechMissionDetailIdRoute: AuthedTechMissionDetailIdRoute,
}

const AuthedTechRouteWithChildren = AuthedTechRoute._addFileChildren(
  AuthedTechRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChefRoute: typeof AuthedChefRouteWithChildren
  AuthedProfilRoute: typeof AuthedProfilRoute
  AuthedTechRoute: typeof AuthedTechRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChefRoute: AuthedChefRouteWithChildren,
  AuthedProfilRoute: AuthedProfilRoute,
  AuthedTechRoute: AuthedTechRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ChangerMotDePasseRoute: ChangerMotDePasseRoute,
  LoginRoute: LoginRoute,
  NonAutoriseRoute: NonAutoriseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
