services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: timeo
      POSTGRES_PASSWORD: timeo123
      POSTGRES_DB: timeo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
